# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastro(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            ".\\Desing/Icon/Logo 120px black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(42, 42, 42)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 40))
        self.header.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header.setStyleSheet("")
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_error = QtWidgets.QFrame(self.header)
        self.frame_error.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_error.setStyleSheet("background-color: rgb(255, 0, 4);\n"
                                       "border-radius: 15px;")
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error)
        self.pushButton_close_error = QtWidgets.QPushButton(self.frame_error)
        self.pushButton_close_error.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_close_error.setStyleSheet("QPushButton {\n"
                                                  "    border-radius: 3px;\n"
                                                  "}\n"
                                                  "QPushButton:hover {\n"
                                                  "    background-color: rgb(154, 9, 9);\n"
                                                  "    color: rgb(255, 255, 255)\n"
                                                  "}\n"
                                                  "\n"
                                                  "QPushButton:pressed {\n"
                                                  "    background-color: rgb(216, 0, 0);\n"
                                                  "    color: rgb(255, 255, 255)\n"
                                                  "}")
        self.pushButton_close_error.setObjectName("pushButton_close_error")
        self.horizontalLayout_3.addWidget(self.pushButton_close_error)
        self.horizontalLayout_2.addWidget(self.frame_error)
        self.verticalLayout.addWidget(self.header)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LoginArea = QtWidgets.QFrame(self.frame_2)
        self.LoginArea.setMaximumSize(QtCore.QSize(600, 500))
        self.LoginArea.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                     "border-radius: 10px;")
        self.LoginArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoginArea.setObjectName("LoginArea")
        self.Title = QtWidgets.QFrame(self.LoginArea)
        self.Title.setGeometry(QtCore.QRect(175, 110, 250, 63))
        self.Title.setMinimumSize(QtCore.QSize(250, 63))
        self.Title.setMaximumSize(QtCore.QSize(250, 63))
        self.Title.setStyleSheet("background-image: url(:/Le-vraria/Le-Vraria 250 px.png);\n"
                                 "background-repeat: no-repeat;\n"
                                 "background-postion: center;\n"
                                 "")
        self.Title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title.setObjectName("Title")
        self.Icon = QtWidgets.QFrame(self.LoginArea)
        self.Icon.setGeometry(QtCore.QRect(240, 10, 120, 120))
        self.Icon.setMinimumSize(QtCore.QSize(120, 120))
        self.Icon.setMaximumSize(QtCore.QSize(10000, 10000))
        self.Icon.setStyleSheet("background-image: url(:/icon/Logo 120px.png);\n"
                                "background-repeat: no-repeat;\n"
                                "background-postion: center;\n"
                                "")
        self.Icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Icon.setObjectName("Icon")
        self.lineEdit_name = QtWidgets.QLineEdit(self.LoginArea)
        self.lineEdit_name.setGeometry(QtCore.QRect(40, 240, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_name.setStyleSheet("QLineEdit{\n"
                                         "    border: 1px solid rgb(176, 176, 176);\n"
                                         "    border-radius: 3px;\n"
                                         "    padding: 10px;\n"
                                         "    backgroud-color: rgb(30, 30, 30);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "}\n"
                                         "\n"
                                         "QLineEdit:hover{\n"
                                         "    border: 1px solid rgb(200, 200, 200);\n"
                                         "}\n"
                                         "\n"
                                         "QLineEdit:focus{\n"
                                         "    border: 1px solid rgb(0, 255, 0);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "}")
        self.lineEdit_name.setMaxLength(50)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_password = QtWidgets.QLineEdit(self.LoginArea)
        self.lineEdit_password.setGeometry(QtCore.QRect(40, 290, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_password.setStyleSheet("QLineEdit{\n"
                                             "    border: 1px solid rgb(176, 176, 176);\n"
                                             "    border-radius: 3px;\n"
                                             "    padding: 10px;\n"
                                             "    backgroud-color: rgb(30, 30, 30);\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "}\n"
                                             "\n"
                                             "QLineEdit:hover{\n"
                                             "    border: 1px solid rgb(200, 200, 200);\n"
                                             "}\n"
                                             "\n"
                                             "QLineEdit:focus{\n"
                                             "    border: 1px solid rgb(0, 255, 0);\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "}")
        self.lineEdit_password.setMaxLength(16)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_cadastrar = QtWidgets.QPushButton(self.LoginArea)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(100, 350, 400, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cadastrar.setFont(font)
        self.pushButton_cadastrar.setStyleSheet("QPushButton {\n"
                                                "    border-radius: 10px;;\n"
                                                "    background-color: rgb(0, 255, 0);\n"
                                                "}\n"
                                                "QPushButton:hover {\n"
                                                "    background-color: rgb(0, 150, 0);\n"
                                                "    color: rgb(255, 255, 255);\n"
                                                "}\n"
                                                "\n"
                                                "QPushButton:pressed {\n"
                                                "    background-color: rgb(0, 50, 0);\n"
                                                "    color: rgb(255, 255, 255);\n"
                                                "}")
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.lineEdit_cpf = QtWidgets.QLineEdit(self.LoginArea)
        self.lineEdit_cpf.setGeometry(QtCore.QRect(310, 240, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_cpf.setFont(font)
        self.lineEdit_cpf.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_cpf.setStyleSheet("QLineEdit{\n"
                                        "    border: 1px solid rgb(176, 176, 176);\n"
                                        "    border-radius: 3px;\n"
                                        "    padding: 10px;\n"
                                        "    backgroud-color: rgb(30, 30, 30);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "\n"
                                        "QLineEdit:hover{\n"
                                        "    border: 1px solid rgb(200, 200, 200);\n"
                                        "}\n"
                                        "\n"
                                        "QLineEdit:focus{\n"
                                        "    border: 1px solid rgb(0, 255, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}")
        self.lineEdit_cpf.setMaxLength(11)
        self.lineEdit_cpf.setObjectName("lineEdit_cpf")
        self.lineEdit_confirmpassword = QtWidgets.QLineEdit(self.LoginArea)
        self.lineEdit_confirmpassword.setGeometry(
            QtCore.QRect(310, 290, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_confirmpassword.setFont(font)
        self.lineEdit_confirmpassword.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_confirmpassword.setStyleSheet("QLineEdit{\n"
                                                    "    border: 1px solid rgb(176, 176, 176);\n"
                                                    "    border-radius: 3px;\n"
                                                    "    padding: 10px;\n"
                                                    "    backgroud-color: rgb(30, 30, 30);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}\n"
                                                    "\n"
                                                    "QLineEdit:hover{\n"
                                                    "    border: 1px solid rgb(200, 200, 200);\n"
                                                    "}\n"
                                                    "\n"
                                                    "QLineEdit:focus{\n"
                                                    "    border: 1px solid rgb(0, 255, 0);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}")
        self.lineEdit_confirmpassword.setMaxLength(16)
        self.lineEdit_confirmpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_confirmpassword.setObjectName("lineEdit_confirmpassword")
        self.pushButton_voltar = QtWidgets.QPushButton(self.LoginArea)
        self.pushButton_voltar.setGeometry(QtCore.QRect(190, 410, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_voltar.setFont(font)
        self.pushButton_voltar.setStyleSheet("QPushButton {\n"
                                             "    border-radius: 10px;;\n"
                                             "    background-color: rgb(100, 100, 100);\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "    background-color: rgb(150, 0, 0);\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:pressed {\n"
                                             "    background-color: rgb(50, 0,0);\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "}")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.horizontalLayout.addWidget(self.LoginArea)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastro"))
        self.label_error.setText(_translate("MainWindow", "Erro"))
        self.pushButton_close_error.setText(_translate("MainWindow", "X"))
        self.lineEdit_name.setPlaceholderText(_translate("MainWindow", "NOME"))
        self.lineEdit_password.setPlaceholderText(
            _translate("MainWindow", "SENHA"))
        self.pushButton_cadastrar.setText(
            _translate("MainWindow", "CADASTRAR"))
        self.lineEdit_cpf.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.lineEdit_confirmpassword.setPlaceholderText(
            _translate("MainWindow", "CONFIRMAÇÃO DE SENHA"))
        self.pushButton_voltar.setText(_translate("MainWindow", "VOLTAR"))
