# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 722)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            ".\\Desing/Icon/Logo 120px black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(42, 42, 42)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 40))
        self.header.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header.setStyleSheet("")
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_error = QtWidgets.QFrame(self.header)
        self.frame_error.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_error.setStyleSheet("background-color: rgb(255, 0, 4);\n"
                                       "border-radius: 15px;")
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error)
        self.pushButton_close_error = QtWidgets.QPushButton(self.frame_error)
        self.pushButton_close_error.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_close_error.setStyleSheet("QPushButton {\n"
                                                  "    border-radius: 3px;\n"
                                                  "}\n"
                                                  "QPushButton:hover {\n"
                                                  "    background-color: rgb(154, 9, 9);\n"
                                                  "    color: rgb(255, 255, 255)\n"
                                                  "}\n"
                                                  "\n"
                                                  "QPushButton:pressed {\n"
                                                  "    background-color: rgb(216, 0, 0);\n"
                                                  "    color: rgb(255, 255, 255)\n"
                                                  "}")
        self.pushButton_close_error.setObjectName("pushButton_close_error")
        self.horizontalLayout_3.addWidget(self.pushButton_close_error)
        self.horizontalLayout_2.addWidget(self.frame_error)
        self.verticalLayout.addWidget(self.header)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LoginArea = QtWidgets.QFrame(self.frame_2)
        self.LoginArea.setMaximumSize(QtCore.QSize(350, 500))
        self.LoginArea.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                     "border-radius: 10px;")
        self.LoginArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoginArea.setObjectName("LoginArea")
        self.Title = QtWidgets.QFrame(self.LoginArea)
        self.Title.setGeometry(QtCore.QRect(50, 140, 250, 63))
        self.Title.setMinimumSize(QtCore.QSize(250, 63))
        self.Title.setMaximumSize(QtCore.QSize(250, 63))
        self.Title.setStyleSheet("background-image: url(:/Le-vraria/Le-Vraria 250 px.png);\n"
                                 "background-postion: center;\n"
                                 "")
        self.Title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title.setObjectName("Title")
        self.Icon = QtWidgets.QFrame(self.LoginArea)
        self.Icon.setGeometry(QtCore.QRect(120, 40, 120, 120))
        self.Icon.setMinimumSize(QtCore.QSize(120, 120))
        self.Icon.setMaximumSize(QtCore.QSize(10000, 10000))
        self.Icon.setStyleSheet("background-image: url(:/icon/Logo 120px.png);\n"
                                "background-postion: center;\n"
                                "")
        self.Icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Icon.setObjectName("Icon")
        self.lineEdit_user = QtWidgets.QLineEdit(self.LoginArea)
        self.lineEdit_user.setGeometry(QtCore.QRect(50, 250, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_user.setStyleSheet("QLineEdit{\n"
                                         "    border: 1px solid rgb(176, 176, 176);\n"
                                         "    border-radius: 3px;\n"
                                         "    padding: 10px;\n"
                                         "    backgroud-color: rgb(30, 30, 30);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "}\n"
                                         "\n"
                                         "QLineEdit:hover{\n"
                                         "    border: 1px solid rgb(200, 200, 200);\n"
                                         "}\n"
                                         "\n"
                                         "QLineEdit:focus{\n"
                                         "    border: 1px solid rgb(0, 255, 0);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "}")
        self.lineEdit_user.setMaxLength(50)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_password = QtWidgets.QLineEdit(self.LoginArea)
        self.lineEdit_password.setGeometry(QtCore.QRect(50, 300, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_password.setStyleSheet("QLineEdit{\n"
                                             "    border: 1px solid rgb(176, 176, 176);\n"
                                             "    border-radius: 3px;\n"
                                             "    padding: 10px;\n"
                                             "    backgroud-color: rgb(30, 30, 30);\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "}\n"
                                             "\n"
                                             "QLineEdit:hover{\n"
                                             "    border: 1px solid rgb(200, 200, 200);\n"
                                             "}\n"
                                             "\n"
                                             "QLineEdit:focus{\n"
                                             "    border: 1px solid rgb(0, 255, 0);\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "}")
        self.lineEdit_password.setMaxLength(16)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_login = QtWidgets.QPushButton(self.LoginArea)
        self.pushButton_login.setGeometry(QtCore.QRect(49, 360, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("QPushButton {\n"
                                            "    border-radius: 10px;;\n"
                                            "    background-color: rgb(0, 255, 0);\n"
                                            "}\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: rgb(0, 150, 0);\n"
                                            "    color: rgb(255, 255, 255);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed {\n"
                                            "    background-color: rgb(0, 50, 0);\n"
                                            "    color: rgb(255, 255, 255);\n"
                                            "}")
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_cadastro = QtWidgets.QPushButton(self.LoginArea)
        self.pushButton_cadastro.setGeometry(QtCore.QRect(60, 410, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cadastro.setFont(font)
        self.pushButton_cadastro.setStyleSheet("QPushButton {\n"
                                               "    border-radius: 10px;;\n"
                                               "    background-color: rgb(100, 100, 100);\n"
                                               "    color: rgb(255, 255, 255);\n"
                                               "}\n"
                                               "QPushButton:hover {\n"
                                               "    background-color: rgb(0, 0, 150);\n"
                                               "    color: rgb(255, 255, 255);\n"
                                               "}\n"
                                               "\n"
                                               "QPushButton:pressed {\n"
                                               "    background-color: rgb(0, 0, 50);\n"
                                               "    color: rgb(255, 255, 255);\n"
                                               "}")
        self.pushButton_cadastro.setObjectName("pushButton_cadastro")
        self.horizontalLayout.addWidget(self.LoginArea)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_2.raise_()
        self.header.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label_error.setText(_translate("MainWindow", "Erro"))
        self.pushButton_close_error.setText(_translate("MainWindow", "X"))
        self.lineEdit_user.setPlaceholderText(
            _translate("MainWindow", "USUÁRIO"))
        self.lineEdit_password.setPlaceholderText(
            _translate("MainWindow", "SENHA"))
        self.pushButton_login.setText(_translate("MainWindow", "LOGIN"))
        self.pushButton_cadastro.setText(_translate("MainWindow", "CADASTRAR"))
