# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainMenu2 .ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 700))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_menu.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_menu.setStyleSheet("background-color: rgb(18, 18, 18);")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_menu)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_2.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_2.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_2.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.pushButton_home = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.pushButton_home.setFont(font)
        self.pushButton_home.setStyleSheet("QPushButton {\n"
                                           "    color: rgb(255, 255, 255)\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover {\n"
                                           "    color: rgb(30, 215, 96);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:pressed {\n"
                                           "    color: rgb(30, 183, 96);\n"
                                           "}")
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout_31.addWidget(self.pushButton_home)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_livros = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.pushButton_livros.setFont(font)
        self.pushButton_livros.setStyleSheet("QPushButton {\n"
                                             "    color: rgb(255, 255, 255)\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:hover {\n"
                                             "    color: rgb(30, 215, 96);\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:pressed {\n"
                                             "    color: rgb(30, 183, 96);\n"
                                             "}")
        self.pushButton_livros.setObjectName("pushButton_livros")
        self.verticalLayout_3.addWidget(self.pushButton_livros)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_creditos = QtWidgets.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.pushButton_creditos.setFont(font)
        self.pushButton_creditos.setStyleSheet("QPushButton {\n"
                                               "    color: rgb(255, 255, 255)\n"
                                               "}\n"
                                               "\n"
                                               "QPushButton:hover {\n"
                                               "    color: rgb(30, 215, 96);\n"
                                               "}\n"
                                               "\n"
                                               "QPushButton:pressed {\n"
                                               "    color: rgb(30, 183, 96);\n"
                                               "}")
        self.pushButton_creditos.setObjectName("pushButton_creditos")
        self.verticalLayout_4.addWidget(self.pushButton_creditos)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_trocas = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.pushButton_trocas.setFont(font)
        self.pushButton_trocas.setStyleSheet("QPushButton {\n"
                                             "    color: rgb(255, 255, 255)\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:hover {\n"
                                             "    color: rgb(30, 215, 96);\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:pressed {\n"
                                             "    color: rgb(30, 183, 96);\n"
                                             "}")
        self.pushButton_trocas.setObjectName("pushButton_trocas")
        self.verticalLayout_5.addWidget(self.pushButton_trocas)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.frame_14 = QtWidgets.QFrame(self.frame_3)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_2.addWidget(self.frame_14)
        self.frame_13 = QtWidgets.QFrame(self.frame_3)
        self.frame_13.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_13.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_logout.setStyleSheet("QPushButton {\n"
                                             "    color: rgb(255, 255, 255)\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:hover {\n"
                                             "    color: rgb(255, 0, 0);\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:pressed {\n"
                                             "    color: rgb(118, 0, 0);\n"
                                             "}")
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.verticalLayout_6.addWidget(self.pushButton_logout)
        self.horizontalLayout_2.addWidget(self.frame_13)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_menu)
        self.frame_show = QtWidgets.QFrame(self.centralwidget)
        self.frame_show.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.frame_show.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_show.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show.setObjectName("frame_show")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_show)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_show)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame_18 = QtWidgets.QFrame(self.page_home)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_18)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_30.addWidget(self.textBrowser)
        self.verticalLayout_29.addWidget(self.frame_18)
        self.frame_16 = QtWidgets.QFrame(self.page_home)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_32.setContentsMargins(0, 7, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.frame_16)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.verticalLayout_32.addWidget(self.textBrowser_5)
        self.verticalLayout_29.addWidget(self.frame_16)
        self.stackedWidget.addWidget(self.page_home)
        self.page_livros = QtWidgets.QWidget()
        self.page_livros.setObjectName("page_livros")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_livros)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_titulo_livro = QtWidgets.QFrame(self.page_livros)
        self.frame_titulo_livro.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_titulo_livro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_titulo_livro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_titulo_livro.setObjectName("frame_titulo_livro")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_titulo_livro)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_titulo_livro)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_7.addWidget(self.textBrowser_2)
        self.verticalLayout_8.addWidget(self.frame_titulo_livro)
        self.frame_livro_pesquisa = QtWidgets.QFrame(self.page_livros)
        self.frame_livro_pesquisa.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_livro_pesquisa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_livro_pesquisa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_livro_pesquisa.setObjectName("frame_livro_pesquisa")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(
            self.frame_livro_pesquisa)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_consulta_livros = QtWidgets.QLineEdit(
            self.frame_livro_pesquisa)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_consulta_livros.setFont(font)
        self.lineEdit_consulta_livros.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_consulta_livros.setStyleSheet("QLineEdit{\n"
                                                    "    border: 1px solid rgb(176, 176, 176);\n"
                                                    "    border-radius: 3px;\n"
                                                    "    padding: 10px;\n"
                                                    "    backgroud-color: rgb(30, 30, 30);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}\n"
                                                    "\n"
                                                    "QLineEdit:hover{\n"
                                                    "    border: 1px solid rgb(200, 200, 200);\n"
                                                    "}\n"
                                                    "\n"
                                                    "QLineEdit:focus{\n"
                                                    "    border: 1px solid rgb(0, 255, 0);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}")
        self.lineEdit_consulta_livros.setMaxLength(50)
        self.lineEdit_consulta_livros.setObjectName("lineEdit_consulta_livros")
        self.horizontalLayout_4.addWidget(self.lineEdit_consulta_livros)
        self.pushButton_consulta_livros = QtWidgets.QPushButton(
            self.frame_livro_pesquisa)
        self.pushButton_consulta_livros.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_consulta_livros.setFont(font)
        self.pushButton_consulta_livros.setStyleSheet("QPushButton {\n"
                                                      "    border-radius: 10px;\n"
                                                      "    background-color: rgb(0, 255, 0);\n"
                                                      "}\n"
                                                      "QPushButton:hover {\n"
                                                      "    background-color: rgb(0, 150, 0);\n"
                                                      "    color: rgb(255, 255, 255);\n"
                                                      "}\n"
                                                      "\n"
                                                      "QPushButton:pressed {\n"
                                                      "    background-color: rgb(0, 50, 0);\n"
                                                      "    color: rgb(255, 255, 255);\n"
                                                      "}")
        self.pushButton_consulta_livros.setObjectName(
            "pushButton_consulta_livros")
        self.horizontalLayout_4.addWidget(self.pushButton_consulta_livros)
        self.verticalLayout_8.addWidget(self.frame_livro_pesquisa)
        self.frame_2 = QtWidgets.QFrame(self.page_livros)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(0, 350))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableWidget_livros = QtWidgets.QTableWidget(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tableWidget_livros.setPalette(palette)
        self.tableWidget_livros.setObjectName("tableWidget_livros")
        self.tableWidget_livros.setColumnCount(5)
        self.tableWidget_livros.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_livros.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_livros.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_livros.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_livros.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_livros.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_6.addWidget(self.tableWidget_livros)
        self.verticalLayout_11.addWidget(self.frame)
        self.frame_buttons_livros = QtWidgets.QFrame(self.frame_2)
        self.frame_buttons_livros.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_livros.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_livros.setObjectName("frame_buttons_livros")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(
            self.frame_buttons_livros)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_voltar = QtWidgets.QFrame(self.frame_buttons_livros)
        self.frame_voltar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_voltar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_voltar.setObjectName("frame_voltar")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_voltar)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_5.addWidget(self.frame_voltar)
        self.frame_inserir = QtWidgets.QFrame(self.frame_buttons_livros)
        self.frame_inserir.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inserir.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inserir.setObjectName("frame_inserir")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_inserir)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_livro_inserir = QtWidgets.QPushButton(
            self.frame_inserir)
        self.pushButton_livro_inserir.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_livro_inserir.setFont(font)
        self.pushButton_livro_inserir.setStyleSheet("QPushButton {\n"
                                                    "    border-radius: 10px;\n"
                                                    "    background-color: rgb(0, 255, 0);\n"
                                                    "}\n"
                                                    "QPushButton:hover {\n"
                                                    "    background-color: rgb(0, 150, 0);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}\n"
                                                    "\n"
                                                    "QPushButton:pressed {\n"
                                                    "    background-color: rgb(0, 50, 0);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}")
        self.pushButton_livro_inserir.setObjectName("pushButton_livro_inserir")
        self.verticalLayout_16.addWidget(self.pushButton_livro_inserir)
        self.horizontalLayout_5.addWidget(self.frame_inserir)
        self.frame_alterar = QtWidgets.QFrame(self.frame_buttons_livros)
        self.frame_alterar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_alterar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_alterar.setObjectName("frame_alterar")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_alterar)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton_livro_alterar = QtWidgets.QPushButton(
            self.frame_alterar)
        self.pushButton_livro_alterar.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_livro_alterar.setFont(font)
        self.pushButton_livro_alterar.setStyleSheet("QPushButton {\n"
                                                    "    border-radius: 10px;\n"
                                                    "    background-color: rgb(0, 255, 0);\n"
                                                    "}\n"
                                                    "QPushButton:hover {\n"
                                                    "    background-color: rgb(0, 150, 0);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}\n"
                                                    "\n"
                                                    "QPushButton:pressed {\n"
                                                    "    background-color: rgb(0, 50, 0);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}")
        self.pushButton_livro_alterar.setObjectName("pushButton_livro_alterar")
        self.verticalLayout_18.addWidget(self.pushButton_livro_alterar)
        self.horizontalLayout_5.addWidget(self.frame_alterar)
        self.frame_excluir = QtWidgets.QFrame(self.frame_buttons_livros)
        self.frame_excluir.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_excluir.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_excluir.setObjectName("frame_excluir")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_excluir)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_livro_excluir = QtWidgets.QPushButton(
            self.frame_excluir)
        self.pushButton_livro_excluir.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_livro_excluir.setFont(font)
        self.pushButton_livro_excluir.setStyleSheet("QPushButton {\n"
                                                    "    border-radius: 10px;\n"
                                                    "    background-color: rgb(0, 255, 0);\n"
                                                    "}\n"
                                                    "QPushButton:hover {\n"
                                                    "    background-color: rgb(0, 150, 0);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}\n"
                                                    "\n"
                                                    "QPushButton:pressed {\n"
                                                    "    background-color: rgb(0, 50, 0);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}")
        self.pushButton_livro_excluir.setObjectName("pushButton_livro_excluir")
        self.verticalLayout_15.addWidget(self.pushButton_livro_excluir)
        self.horizontalLayout_5.addWidget(self.frame_excluir)
        self.verticalLayout_11.addWidget(
            self.frame_buttons_livros, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page_livros)
        self.page_creditos = QtWidgets.QWidget()
        self.page_creditos.setObjectName("page_creditos")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_creditos)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_titulo_credito = QtWidgets.QFrame(self.page_creditos)
        self.frame_titulo_credito.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_titulo_credito.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_titulo_credito.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_titulo_credito.setObjectName("frame_titulo_credito")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(
            self.frame_titulo_credito)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_titulo_credito)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_14.addWidget(self.textBrowser_3)
        self.verticalLayout_13.addWidget(self.frame_titulo_credito)
        self.frame_credito_pesquisa = QtWidgets.QFrame(self.page_creditos)
        self.frame_credito_pesquisa.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_credito_pesquisa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_credito_pesquisa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_credito_pesquisa.setObjectName("frame_credito_pesquisa")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(
            self.frame_credito_pesquisa)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_consultacliente = QtWidgets.QLineEdit(
            self.frame_credito_pesquisa)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_consultacliente.setFont(font)
        self.lineEdit_consultacliente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_consultacliente.setStyleSheet("QLineEdit{\n"
                                                    "    border: 1px solid rgb(176, 176, 176);\n"
                                                    "    border-radius: 3px;\n"
                                                    "    padding: 10px;\n"
                                                    "    backgroud-color: rgb(30, 30, 30);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}\n"
                                                    "\n"
                                                    "QLineEdit:hover{\n"
                                                    "    border: 1px solid rgb(200, 200, 200);\n"
                                                    "}\n"
                                                    "\n"
                                                    "QLineEdit:focus{\n"
                                                    "    border: 1px solid rgb(0, 255, 0);\n"
                                                    "    color: rgb(255, 255, 255);\n"
                                                    "}")
        self.lineEdit_consultacliente.setMaxLength(50)
        self.lineEdit_consultacliente.setObjectName("lineEdit_consultacliente")
        self.horizontalLayout_3.addWidget(self.lineEdit_consultacliente)
        self.pushButton_consulta_2 = QtWidgets.QPushButton(
            self.frame_credito_pesquisa)
        self.pushButton_consulta_2.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton_consulta_2.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_consulta_2.setFont(font)
        self.pushButton_consulta_2.setStyleSheet("QPushButton {\n"
                                                 "    border-radius: 10px;\n"
                                                 "    background-color: rgb(0, 255, 0);\n"
                                                 "}\n"
                                                 "QPushButton:hover {\n"
                                                 "    background-color: rgb(0, 150, 0);\n"
                                                 "    color: rgb(255, 255, 255);\n"
                                                 "}\n"
                                                 "\n"
                                                 "QPushButton:pressed {\n"
                                                 "    background-color: rgb(0, 50, 0);\n"
                                                 "    color: rgb(255, 255, 255);\n"
                                                 "}")
        self.pushButton_consulta_2.setObjectName("pushButton_consulta_2")
        self.horizontalLayout_3.addWidget(self.pushButton_consulta_2)
        self.verticalLayout_13.addWidget(self.frame_credito_pesquisa)
        self.frame_20 = QtWidgets.QFrame(self.page_creditos)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_4 = QtWidgets.QFrame(self.frame_20)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 350))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tableWidget_Clientes = QtWidgets.QTableWidget(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ToolTipText, brush)
        self.tableWidget_Clientes.setPalette(palette)
        self.tableWidget_Clientes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_Clientes.setObjectName("tableWidget_Clientes")
        self.tableWidget_Clientes.setColumnCount(3)
        self.tableWidget_Clientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_Clientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_Clientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_Clientes.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_7.addWidget(self.tableWidget_Clientes)
        self.verticalLayout_23.addWidget(self.frame_4)
        self.frame_buttons_clientes = QtWidgets.QFrame(self.frame_20)
        self.frame_buttons_clientes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_clientes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_clientes.setObjectName("frame_buttons_clientes")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(
            self.frame_buttons_clientes)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_voltar_2 = QtWidgets.QFrame(self.frame_buttons_clientes)
        self.frame_voltar_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_voltar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_voltar_2.setObjectName("frame_voltar_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_voltar_2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_8.addWidget(self.frame_voltar_2)
        self.frame_inserir_2 = QtWidgets.QFrame(self.frame_buttons_clientes)
        self.frame_inserir_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inserir_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inserir_2.setObjectName("frame_inserir_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_inserir_2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.pushButton_clientes_inserir = QtWidgets.QPushButton(
            self.frame_inserir_2)
        self.pushButton_clientes_inserir.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_clientes_inserir.setFont(font)
        self.pushButton_clientes_inserir.setStyleSheet("QPushButton {\n"
                                                       "    border-radius: 10px;\n"
                                                       "    background-color: rgb(0, 255, 0);\n"
                                                       "}\n"
                                                       "QPushButton:hover {\n"
                                                       "    background-color: rgb(0, 150, 0);\n"
                                                       "    color: rgb(255, 255, 255);\n"
                                                       "}\n"
                                                       "\n"
                                                       "QPushButton:pressed {\n"
                                                       "    background-color: rgb(0, 50, 0);\n"
                                                       "    color: rgb(255, 255, 255);\n"
                                                       "}")
        self.pushButton_clientes_inserir.setObjectName(
            "pushButton_clientes_inserir")
        self.verticalLayout_20.addWidget(self.pushButton_clientes_inserir)
        self.horizontalLayout_8.addWidget(self.frame_inserir_2)
        self.frame_alterar_2 = QtWidgets.QFrame(self.frame_buttons_clientes)
        self.frame_alterar_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_alterar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_alterar_2.setObjectName("frame_alterar_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_alterar_2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.pushButton_clientes_alterar = QtWidgets.QPushButton(
            self.frame_alterar_2)
        self.pushButton_clientes_alterar.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_clientes_alterar.setFont(font)
        self.pushButton_clientes_alterar.setStyleSheet("QPushButton {\n"
                                                       "    border-radius: 10px;\n"
                                                       "    background-color: rgb(0, 255, 0);\n"
                                                       "}\n"
                                                       "QPushButton:hover {\n"
                                                       "    background-color: rgb(0, 150, 0);\n"
                                                       "    color: rgb(255, 255, 255);\n"
                                                       "}\n"
                                                       "\n"
                                                       "QPushButton:pressed {\n"
                                                       "    background-color: rgb(0, 50, 0);\n"
                                                       "    color: rgb(255, 255, 255);\n"
                                                       "}")
        self.pushButton_clientes_alterar.setObjectName(
            "pushButton_clientes_alterar")
        self.verticalLayout_21.addWidget(self.pushButton_clientes_alterar)
        self.horizontalLayout_8.addWidget(self.frame_alterar_2)
        self.frame_excluir_2 = QtWidgets.QFrame(self.frame_buttons_clientes)
        self.frame_excluir_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_excluir_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_excluir_2.setObjectName("frame_excluir_2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_excluir_2)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.pushButton_clientes_excluir = QtWidgets.QPushButton(
            self.frame_excluir_2)
        self.pushButton_clientes_excluir.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_clientes_excluir.setFont(font)
        self.pushButton_clientes_excluir.setStyleSheet("QPushButton {\n"
                                                       "    border-radius: 10px;\n"
                                                       "    background-color: rgb(0, 255, 0);\n"
                                                       "}\n"
                                                       "QPushButton:hover {\n"
                                                       "    background-color: rgb(0, 150, 0);\n"
                                                       "    color: rgb(255, 255, 255);\n"
                                                       "}\n"
                                                       "\n"
                                                       "QPushButton:pressed {\n"
                                                       "    background-color: rgb(0, 50, 0);\n"
                                                       "    color: rgb(255, 255, 255);\n"
                                                       "}")
        self.pushButton_clientes_excluir.setObjectName(
            "pushButton_clientes_excluir")
        self.verticalLayout_22.addWidget(self.pushButton_clientes_excluir)
        self.horizontalLayout_8.addWidget(self.frame_excluir_2)
        self.verticalLayout_23.addWidget(self.frame_buttons_clientes)
        self.verticalLayout_13.addWidget(self.frame_20)
        self.stackedWidget.addWidget(self.page_creditos)
        self.page_trocas = QtWidgets.QWidget()
        self.page_trocas.setObjectName("page_trocas")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_trocas)
        self.verticalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_12.setSpacing(7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_titulo_troca = QtWidgets.QFrame(self.page_trocas)
        self.frame_titulo_troca.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_titulo_troca.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_titulo_troca.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_titulo_troca.setObjectName("frame_titulo_troca")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_titulo_troca)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.frame_titulo_troca)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_10.addWidget(self.textBrowser_4)
        self.verticalLayout_12.addWidget(self.frame_titulo_troca)
        self.frame_troca_pesquisa = QtWidgets.QFrame(self.page_trocas)
        self.frame_troca_pesquisa.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_troca_pesquisa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_troca_pesquisa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_troca_pesquisa.setObjectName("frame_troca_pesquisa")
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.frame_troca_pesquisa)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_consultatroca = QtWidgets.QLineEdit(
            self.frame_troca_pesquisa)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_consultatroca.setFont(font)
        self.lineEdit_consultatroca.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_consultatroca.setStyleSheet("QLineEdit{\n"
                                                  "    border: 1px solid rgb(176, 176, 176);\n"
                                                  "    border-radius: 3px;\n"
                                                  "    padding: 10px;\n"
                                                  "    backgroud-color: rgb(30, 30, 30);\n"
                                                  "    color: rgb(255, 255, 255);\n"
                                                  "}\n"
                                                  "\n"
                                                  "QLineEdit:hover{\n"
                                                  "    border: 1px solid rgb(200, 200, 200);\n"
                                                  "}\n"
                                                  "\n"
                                                  "QLineEdit:focus{\n"
                                                  "    border: 1px solid rgb(0, 255, 0);\n"
                                                  "    color: rgb(255, 255, 255);\n"
                                                  "}")
        self.lineEdit_consultatroca.setMaxLength(50)
        self.lineEdit_consultatroca.setReadOnly(False)
        self.lineEdit_consultatroca.setObjectName("lineEdit_consultatroca")
        self.horizontalLayout.addWidget(self.lineEdit_consultatroca)
        self.pushButton_consulta_trocas = QtWidgets.QPushButton(
            self.frame_troca_pesquisa)
        self.pushButton_consulta_trocas.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_consulta_trocas.setFont(font)
        self.pushButton_consulta_trocas.setStyleSheet("QPushButton {\n"
                                                      "    border-radius: 10px;\n"
                                                      "    background-color: rgb(0, 255, 0);\n"
                                                      "}\n"
                                                      "QPushButton:hover {\n"
                                                      "    background-color: rgb(0, 150, 0);\n"
                                                      "    color: rgb(255, 255, 255);\n"
                                                      "}\n"
                                                      "\n"
                                                      "QPushButton:pressed {\n"
                                                      "    background-color: rgb(0, 50, 0);\n"
                                                      "    color: rgb(255, 255, 255);\n"
                                                      "}")
        self.pushButton_consulta_trocas.setObjectName(
            "pushButton_consulta_trocas")
        self.horizontalLayout.addWidget(self.pushButton_consulta_trocas)
        self.verticalLayout_12.addWidget(self.frame_troca_pesquisa)
        self.frame_17 = QtWidgets.QFrame(self.page_trocas)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_15 = QtWidgets.QFrame(self.frame_17)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 350))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableWidget_Trocas = QtWidgets.QTableWidget(self.frame_15)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tableWidget_Trocas.setPalette(palette)
        self.tableWidget_Trocas.setObjectName("tableWidget_Trocas")
        self.tableWidget_Trocas.setColumnCount(6)
        self.tableWidget_Trocas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_Trocas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Trocas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_Trocas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_Trocas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_Trocas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_Trocas.setHorizontalHeaderItem(5, item)
        self.horizontalLayout_9.addWidget(self.tableWidget_Trocas)
        self.verticalLayout_28.addWidget(self.frame_15)
        self.frame_buttons_trocas = QtWidgets.QFrame(self.frame_17)
        self.frame_buttons_trocas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_trocas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_trocas.setObjectName("frame_buttons_trocas")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(
            self.frame_buttons_trocas)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_voltar_3 = QtWidgets.QFrame(self.frame_buttons_trocas)
        self.frame_voltar_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_voltar_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_voltar_3.setObjectName("frame_voltar_3")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_voltar_3)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_10.addWidget(self.frame_voltar_3)
        self.frame_inserir_3 = QtWidgets.QFrame(self.frame_buttons_trocas)
        self.frame_inserir_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inserir_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inserir_3.setObjectName("frame_inserir_3")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_inserir_3)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_10.addWidget(self.frame_inserir_3)
        self.frame_alterar_3 = QtWidgets.QFrame(self.frame_buttons_trocas)
        self.frame_alterar_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_alterar_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_alterar_3.setObjectName("frame_alterar_3")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_alterar_3)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_10.addWidget(self.frame_alterar_3)
        self.frame_excluir_3 = QtWidgets.QFrame(self.frame_buttons_trocas)
        self.frame_excluir_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_excluir_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_excluir_3.setObjectName("frame_excluir_3")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_excluir_3)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.pushButton_trocas_fazertroca = QtWidgets.QPushButton(
            self.frame_excluir_3)
        self.pushButton_trocas_fazertroca.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_trocas_fazertroca.setFont(font)
        self.pushButton_trocas_fazertroca.setStyleSheet("QPushButton {\n"
                                                        "    border-radius: 10px;\n"
                                                        "    background-color: rgb(0, 255, 0);\n"
                                                        "}\n"
                                                        "QPushButton:hover {\n"
                                                        "    background-color: rgb(0, 150, 0);\n"
                                                        "    color: rgb(255, 255, 255);\n"
                                                        "}\n"
                                                        "\n"
                                                        "QPushButton:pressed {\n"
                                                        "    background-color: rgb(0, 50, 0);\n"
                                                        "    color: rgb(255, 255, 255);\n"
                                                        "}")
        self.pushButton_trocas_fazertroca.setObjectName(
            "pushButton_trocas_fazertroca")
        self.verticalLayout_27.addWidget(self.pushButton_trocas_fazertroca)
        self.horizontalLayout_10.addWidget(self.frame_excluir_3)
        self.verticalLayout_28.addWidget(self.frame_buttons_trocas)
        self.verticalLayout_12.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.page_trocas)
        self.verticalLayout_9.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_show)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Le-Vraria"))
        self.pushButton_home.setText(_translate("MainWindow", "HOME"))
        self.pushButton_livros.setText(_translate("MainWindow", "LIVROS"))
        self.pushButton_creditos.setText(_translate("MainWindow", "CLIENTES"))
        self.pushButton_trocas.setText(_translate("MainWindow", "TROCAS"))
        self.pushButton_logout.setText(_translate("MainWindow", "LOGOUT"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/Le-vraria/Le-Vraria 250 px.png\" /></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#ffffff;\"><br /></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#ffffff;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">• O sistema lê-vraria consiste em um sistema gerenciador de um livraria comunitária, onde cada doação de livro gera um crédito que posteriormente pode ser trocado por outros livros. O sistema foi desenvolvido em Python juntamente com um SGBD.</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#ffffff;\"><br /></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">O menu principal está dividido em 4 abas:</span><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\"> HOME, LIVROS, CLIENTES </span><span style=\" font-size:12pt; color:#ffffff;\">e</span><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\"> TROCAS.</span></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">HOME:</span><span style=\" font-size:12pt; color:#ffffff;\"> Você está aqui!</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#ffffff;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">LIVROS:</span><span style=\" font-size:12pt; color:#ffffff;\"> Possui o registro de todos livros presentes no banco de dados. Nessa aba você pode fazer uma troca de livro por pontos , alterar dados ou excluir um livro.</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#ffffff;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">CLIENTES:</span><span style=\" font-size:12pt; color:#ffffff;\"> Possui o registro de todos clientes presentes no banco de dados. Nessa aba é possivel cadastrar, alterar ou exlcluir quanquer cliente.</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#ffffff;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">TROCA:</span><span style=\" font-size:12pt; color:#ffffff;\"> Possui o registro de todas as trocas realizadas e que estão registradas no banco de dados. Nessa aba é possível realizar trocas.</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#46dd00;\">CSI-440 - BANCO DE DADOS 1 - 2021/1                                                            Alunos: Felipe Delfim Machado, Henrique Medeiros Malvar de Oliveira, Thalysson</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">LIVROS</span></p></body></html>"))
        self.lineEdit_consulta_livros.setPlaceholderText(
            _translate("MainWindow", "ID DO LIVRO"))
        self.pushButton_consulta_livros.setText(
            _translate("MainWindow", "CONSULTAR"))
        item = self.tableWidget_livros.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_livros.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Titulo"))
        item = self.tableWidget_livros.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Autor"))
        item = self.tableWidget_livros.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tier"))
        item = self.tableWidget_livros.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Em Estoque"))
        self.pushButton_livro_inserir.setText(
            _translate("MainWindow", "RECEBER LVIRO"))
        self.pushButton_livro_alterar.setText(
            _translate("MainWindow", "ALTERAR LIVRO"))
        self.pushButton_livro_excluir.setText(
            _translate("MainWindow", "EXCLUIR LIVRO"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">CLIENTES</span></p></body></html>"))
        self.lineEdit_consultacliente.setPlaceholderText(
            _translate("MainWindow", "CPF DO CLIENTE A CONSULTAR"))
        self.pushButton_consulta_2.setText(
            _translate("MainWindow", "CONSULTAR"))
        item = self.tableWidget_Clientes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget_Clientes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CPF"))
        item = self.tableWidget_Clientes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Creditos"))
        self.pushButton_clientes_inserir.setText(
            _translate("MainWindow", "ADICIONAR CLIENTE"))
        self.pushButton_clientes_alterar.setText(
            _translate("MainWindow", "ALTERAR CLIENTE"))
        self.pushButton_clientes_excluir.setText(
            _translate("MainWindow", "EXCLUIR CLIENTE"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">TROCAS</span></p></body></html>"))
        self.lineEdit_consultatroca.setPlaceholderText(
            _translate("MainWindow", "ID DA TROCA"))
        self.pushButton_consulta_trocas.setText(
            _translate("MainWindow", "CONSULTAR"))
        item = self.tableWidget_Trocas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID TROCA"))
        item = self.tableWidget_Trocas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID LIVRO"))
        item = self.tableWidget_Trocas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CPF CLIENTE"))
        item = self.tableWidget_Trocas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CPF FUNCIONÁRIO"))
        item = self.tableWidget_Trocas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TIER LIVRO"))
        item = self.tableWidget_Trocas.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "DATA TROCA"))
        self.pushButton_trocas_fazertroca.setText(
            _translate("MainWindow", "FAZER TROCA"))
